root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -tags 'fts5' -o ./tmp/main ."
  entrypoint = "./tmp/main"
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "sample-media", "vendor"]
  delay = 1000

[misc]
  clean_on_exit = true
