apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc-media.yaml
  - pvc-database.yaml
  - service.yaml

images:
- name: ghcr.io/djryanj/media-viewer
  # newName: docker.io/bitnamilegacy/kubernetes-event-exporter
  newTag: "v0.1.4"